### ISSUE TITLE
SoftwareSerial not supported by Linkit One replacement solution?

### ISSUE THREAD

**Issue by howardweng** [Seeed-Studio/RFID_Library#8] opened 2016-09-14 11:25 UTC
can you please help. I have Arduino board working, but I need to have Linkit One board working too. but my problem is that Linkit one does not support <SoftwareSerial.h> but have serial port TX.RX. 

Can you have your technical support to help me to modify this code to support Linkit One? thanks for helping. 
# include <SoftwareSerial.h>

SoftwareSerial LoRaUART(10, 11); // to TX, to RX

void setup() {
  Serial.begin(9600);

  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }
  Serial.println("Serial Ready");

  LoRaUART.begin(9600);
  LoRaUART.println("AT");

  while (!LoRaUART.available()) {
    ;
  }
  Serial.println("LoRa Serial Ready");
}

void loop() {

  //LoRaUART.println("AT+DTX=6,\"abcdef\"");
  //LoRaUART.println("AT+DTX=5,\"33/88\"");
  //Serial.println("ATDTX 33/88");
  LoRaUART.println("AT+DTX=16,1234567890abcdef");
  delay(10*1000);
}

**Comment by s-light** [comment] 2022-05-16 10:04
it is a duplicate of #4 
and the linkit products are end of life.
please move your request there or in the [user forums](https://forum.seeedstudio.com/c/end-of-life-products-services/linkit/22) and please close this one.

**Closed as completed** 2024-10-15 06:53 UTC
Labels: UAY, RFID_Library
